### ISSUE TITLE
Initial Wiki

### ISSUE THREAD

**Issue by foleycolin00** [RPHolloway/expertiza#25]
- [x] Intro
- [x] Previous Implementation (Design Pattern, Methods, etc)
- [x] Issues
- [x] Proposed Solution(s)
- [x] Test Plan

(Space for code)

**Comment by foleycolin00** [comment]
Things we are responsible for:
- remove debugging comments
- change update to edit
- private methods
- tests
- making sure that text comments work -> test

**Comment by pjloheide** [comment]
Created [wiki page](https://expertiza.csc.ncsu.edu/index.php/CSC/ECE_517_Spring_2020_-_E2025:_Issues_Related_to_Meta_-_Reviewing) for the project on expertiza.
