### ISSUE TITLE
Checking "Has meta-review Limit" box defaults allowed/required to 3.

### ISSUE THREAD

**Issue by Ackleberry** [RPHolloway/expertiza#28]
"Has meta-review limit" box is located in the "Review Strategy" tab. The UI should default "allowed" and "required" to 3.

The user should be allowed to change the default value of 3 to any value they wish before submitting.

Checking the box shows required as 0
![image](https://user-images.githubusercontent.com/13756667/80164812-07cb8600-85a8-11ea-9e75-e7ddd477d6bd.png)

**Comment by foleycolin00** [comment]
Already Fixed by E1997
