### ISSUE TITLE
Remove all debug comments in UI

### ISSUE THREAD

**Issue by Ackleberry** [RPHolloway/expertiza#32]
These comments were added in this [pull request](https://github.com/expertiza/expertiza/pull/1645).
Related [Wiki page](http://wiki.expertiza.ncsu.edu/index.php/CSC/ECE_517_Fall_2019_-_E1997._Issues_related_to_meta-reviewing) for pull request.

**Comment by foleycolin00** [comment]
Tone analysis?
also deals with the extra<\br>
