### ISSUE TITLE
"Update" existing meta-review should be modified to "Edit".

### ISSUE THREAD

**Issue by Ackleberry** [RPHolloway/expertiza#33]
Based off this [pull request](https://github.com/expertiza/expertiza/pull/1645).
Related [Wiki page](http://wiki.expertiza.ncsu.edu/index.php/CSC/ECE_517_Fall_2019_-_E1997._Issues_related_to_meta-reviewing) for pull request.

![metaReviewUpdateIssue](https://user-images.githubusercontent.com/39815071/78736865-ca15fe80-7913-11ea-8fd3-4db17bd31670.png)
the "update" button can be changed to "Edit".

**Comment by foleycolin00** [comment]
I believe PJ said this was already fixed by the previous team
