### ISSUE TITLE
Create RSpec tests for E1997's (Fall 2019) implementation.

### ISSUE THREAD

**Issue by Ackleberry** [RPHolloway/expertiza#35]
Fall 2019 [pull request](https://github.com/expertiza/expertiza/pull/1645).
Related [E1997's Wiki page](http://wiki.expertiza.ncsu.edu/index.php/CSC/ECE_517_Fall_2019_-_E1997._Issues_related_to_meta-reviewing) for pull request.

No test were created for E1997's submission. RSpec tests need to be created to understand the current state of meta-reviewing functionality. This issue should only cover existing functionality. All E2025's issues should have their own respective RSpec tests added. This should allow for high coverage at the end of the project.

**Comment by foleycolin00** [comment]
1. If I create an assignment, then the number of meta-reviews is set to null.

2. If 'Use metareview deadline' is not enabled in the due dates tab, then the meta-review fields in the review strategy tab are not visible.

3. If the metareview limit on the assignment is set to 3, then a student will see they need to submit 3 meta reviews

4. If the metareview deadline is enabled, the assignment cannot be created without a metareview rubric

5. If the assignment created is in a stage that does not have metareview enabled, a metareview cannot be created

6. If the assignment does not have any legal meta reviews, then the "Request a new metareview to perform" button is not visible

7. A student should not be able to request a metareview if they have reached the limit of their allowed reviews

8. A student should be able to request a metareview if they are above their required but below their allowed reviews

9. A student should not be able to request a metareview about their own work. 

10. A student should not be able to request a metareview about themselves. 

11. If there is a valid metareview to perform related to two other students, then the metareview should be able to be performed.

12. If a student has requested two metareviewes but have not submitted it, then they should not be able to request a new metareview.

13. If the metareview limit on the assignment is set to 1 then a student should not be able to request a second meta review
